#!/bin/bash

if [ "$#" -eq 0 ] || [ "$1" = "--help" ]
then
	echo "mod_compile <xyz>.clsp"
	exit 1
fi

CLSP=$(basename $1)
DIR=$(dirname $1)
OUTDIR=$DIR/output

if [ ! -f "$DIR/$CLSP" ]
then
	echo $DIR/$CLSP: file not found
	exit 1
fi

if [ ! -d "$OUTDIR" ]
then 
	mkdir "$OUTDIR"
fi

~/.cargo/bin/run -O -i "$DIR/include/" -i "$OUTDIR/" "$DIR/$CLSP" > "$OUTDIR/$CLSP.clvm"
if [ "$(head -c 1 "$OUTDIR/$CLSP.clvm")" != "(" ]
then
	echo "Compilation error:"
	cat "$OUTDIR/$CLSP.clvm"
	echo ""
	exit 1
fi

~/.cargo/bin/opc "$OUTDIR/$CLSP.clvm" > "$OUTDIR/$CLSP.hex"
~/.cargo/bin/opc -H "$OUTDIR/$CLSP.clvm" > "$OUTDIR/$CLSP.hash"
xxd -r -p "$OUTDIR/$CLSP.hash" "$OUTDIR/$CLSP.hash.bin"

echo Success!
